name: material3_expressive_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0-129.0.dev

dependencies:
  flutter:
    sdk: flutter
  material3_expressive:
    path: ../
  material_symbols_icons: ^4.2815.0
  logging: ^1.3.0
  device_info_plus: ^11.4.0
  collection: ^1.19.1
  skeletonizer: 2.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
