name: _
publish_to: none

environment:
  sdk: ^3.8.0-219.0.dev

workspace:

  # Packages
  - packages/widgets
  - packages/material
  - packages/dynamic_color

  # Apps
  - packages/material/example

dependency_overrides:
  # Override pinned SDK dependency
  # material_color_utilities v0.12.0 introduced new expressive on-colors spec
  material_color_utilities: ^0.12.0
