name: _
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

workspace:

  # Packages
  - packages/widgets
  - packages/material
  - packages/mcu
  # - packages/material3_baseline
  - packages/material3_expressive
  # - packages/rounded_polygon
  - packages/shapes_dart

  # Apps
  - apps/material_theme_builder
  - packages/material3_expressive/example

dependency_overrides:
  # Override pinned SDK dependency
  # material_color_utilities v0.12.0 introduced new expressive on-colors spec
  material_color_utilities: ^0.12.0
