name: material_theme_builder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  mcu:
    path: ../../packages/mcu
  material3_expressive:
    path: ../../packages/material3_expressive
  material_symbols_icons: ^4.2815.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  replay_bloc: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  slang_build_runner: ^4.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/RobotoFlex/OFL.txt
  fonts:
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/RobotoFlex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf

