name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter
  material:
    path: ../
  simple_icons: ^10.1.3
  http: ^1.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
